#!/usr/bin/env bash
#Com
x=1
while [ $x != 21 ];
do 
case $x in
5) echo "bad luck from China"
echo $x
;;
10) echo "bad luck from Japan"
echo $x
;;
18) echo "bad luck from Itay"
echo $x
;;
*) echo "$x"
;;
esac
x=$((x+1))
done
