#!/usr/bin/env bash
#test
touch /var/run/myscript.pid 
while :
do
    echo "To infinity and beyond"
done
trap "echo I hate the kill command" 15
trap "echo Y U no love me?!" 2
trap "rm /var/run/myscript.pid ; exit" 
