#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process.

case ${1} in

start)
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "manage_my_process started"
;;
stop)
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
;;
restart) 
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "manage_my_process restarted"
;;
esac

